### PR TITLE
Request time increase to 15 second

### LINKED ISSUE #35: Exponentially throttle polling when rate limited by CoinGecko
## Actual
If you view the `pm2 logs` on our production server, you will notice a lot of these errors:
```
response: {
    status: 429,
    statusText: 'Too Many Requests',
    ...
config: {
    url: 'https://api.coingecko.com/api/v3/coins/list?include_platform=true',
    ...
```
This is probably happening because Coingecko is rate limiting us (although we hit their server every five seconds which seems well [within their prescribed limit](https://www.coingecko.com/en/api_terms) but maybe their definition of rate limit has some details that i couldn't grasp).
image

## Expected
Since we get rate limited a lot, we should slow down our polling whenever we face a rate limiting error from CG.

### PR DESCRIPTION
**Pull request by Shapokhan**
fixes #35

### CODE REVIEW

**Comment by Shapokhan** [comment]
@omeryousaf Bhai, I have checked the response of API at different times (5 seconds, 10 seconds, 15 seconds).  The behavior is the same at 10 seconds as well and I got the same error(response_status: 429, response_message: Too many requests). But there it is working fine on 15 seconds and I have tested it for 5 minutes. 
The question is if it is working fine on the delay of 15 seconds still need exponential throttling?

**Comment by Shapokhan** [comment]
@omeryousaf Bhai, there is also an npm package for rate-limiting purposes. 
[https://www.npmjs.com/package/express-rate-limit]
will you recommend that should we go for this package?

**Comment by omeryousaf** [comment]
> @omeryousaf Bhai, there is also an npm package for rate-limiting purposes.
> [https://www.npmjs.com/package/express-rate-limit]
> will you recommend that should we go for this package?

@Shapokhan this seems like a library meant for applications that want to start rate limiting users. I don't think that's our issue. Our issue is how to get around rate limiting we are facing from one of the services we use.

**Comment by omeryousaf** [comment]
> @omeryousaf Bhai, I have checked the response of API at different times (5 seconds, 10 seconds, 15 seconds). The behavior is the same at 10 seconds as well and I got the same error(response_status: 429, response_message: Too many requests). But there it is working fine on 15 seconds and I have tested it for 5 minutes.
> The question is if it is working fine on the delay of 15 seconds still need exponential throttling?

@Shapokhan how many polling services can we optimize by manual testing ? What if we have another external api service to poll or a website to scrape ? Unless we are make our polling process more mature and adaptable to the rate limiting it has to face, we will always be left with only manual testing to find optimal polling rates. Also, what if Coingecko does not even mind being polled every 12 seconds but if you did not check that interval you would not find out. But with automating polling rate adjustment, you could even add logic to continue adjusting until u find the rate where if you increase by 1 second, you start getting 429 errors i-e you could find best polling rate correct to nearest integer.

**Comment by Shapokhan** [comment]
@omeryousaf I have changed "setTimeInterval" to "setTimeOut". The reason for this change is that in the case of setTiminterval if we need to change the interval we have to stop the setTimeInterval function first and then set the new interval and call it again. 
While in the case of setTimeOut as we know that it calls only once for a specific interval and for API calls we have to call it recursively so we can set intervals each time according to our requirement(In normal case 5 seconds and in case of rate limit we can increase our interval for API call").

**Pull request merged**
